

### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "grace",
  "password": "grace"
}

###
### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "grace",
  "password": "grace",
  "roles": ["ROLE_WRITE", "ROLE_READ"]
}

###
### 자동완성 조회 기능
GET http://localhost:8080/company/autocomplete?keyword
Accept: application/json

###
### 배당금 저장
POST http://localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfV1JJVEUiLCJST0xFX1JFQUQiXSwiaWF0IjoxNjgzNTU2Nzg0LCJleHAiOjE2ODM1NjAzODR9.j-HoFsW9_55qqzv3bLbUCFWwLBc8Cq5hDHTNzeo1-BoyA_TIlw1B1Q4j2UY1S6g8_tLUoniERu6EEQFuV6FKBw

{
  "ticker": "O"
}

###
### 회사 조회
GET http://localhost:8080/company
Accept: application/json

###
### 특정 회사 배당금 조회
GET http://localhost:8080/finance/dividend/3M Company
Accept: application/json

### 회사 삭제
DELETE http://localhost:8080/company/MMM
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfV1JJVEUiLCJST0xFX1JFQUQiXSwiaWF0IjoxNjgzNTU2Nzg0LCJleHAiOjE2ODM1NjAzODR9.j-HoFsW9_55qqzv3bLbUCFWwLBc8Cq5hDHTNzeo1-BoyA_TIlw1B1Q4j2UY1S6g8_tLUoniERu6EEQFuV6FKBw
